[project]
name = "mcp-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "langchain-groq>=0.3.7",
    "langchain-openai>=0.3.32",
    "mcp-use>=1.3.10",
]
